#!/bin/bash

WALLPAPER=$HOME/.wallpaper

if [ -z "$1" ]; then
    echo "Use a path to an image."
    exit 1
else
    if [ -f "$1" ]; then
        echo "Replacing the wallpaper."
        [ -f $WALLPAPER ] && rm $WALLPAPER
        ln -s "$(realpath $1)" "$WALLPAPER"
    else
        echo "Invalid option."
        echo "The argument must be a file."
        exit 1
    fi
fi

i3-msg exec ~/.local/bin/feh-wrapper 1>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
    echo "OK."
else
    echo "FAIL"
    exit 1
fi
